# Numpy

## install

In [1]:
# terminal commands ausfuehren mit `!`

!mkdir test

mkdir: test: File exists


In [2]:
# python module installieren fuer die 'richtige' python-version,
# die auch im Notebook verwendet wird

import sys

!{sys.executable} -m pip install numpy

# equivalent to:
# /Users/<username>/miniconda3/bin/python -m pip install numpy
# or similar

## Import

In [3]:
import numpy as np

## Numpy-Arrays vs. Listen

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
l = [1, 2, 3, 4]

In [7]:
l

[1, 2, 3, 4]

### elementweise Operationen

In [8]:
a_1 = np.array([1,   2,   3,   4])
a_2 = np.array([200, 300, 400, 500])

a_1 + a_2

array([201, 302, 403, 504])

In [9]:
l_1 = [1, 2, 3, 4]
l_2 = [200, 300, 400, 500]

l_1 + l_2 # listen muessten elementweise verrechnet werden durch loops

[1, 2, 3, 4, 200, 300, 400, 500]

In [10]:
# array concatenation
np.concatenate([a_1, a_2])

array([  1,   2,   3,   4, 200, 300, 400, 500])

In [11]:
# --------------------------------------------------------
# Jupyter shortcuts for auto-completion and documentation:

# np.conc # -> Tab --> auto-completion

# np.concatenate() # mit cursor innerhalb der klammern:
# Shift-Tab 

In [12]:
# elementweise Operationen funktionieren mit (fast) allen moeglichen Funktionen

print(a_1 + a_2, '\n')

print(a_1 - a_2, '\n')

print(a_1 * a_2, '\n')

print(a_2 ** a_1, '\n')

print(np.array([2, 5, 8, 13]) > np.array([3, 4, 10, 12]), '\n')

[201 302 403 504] 

[-199 -298 -397 -496] 

[ 200  600 1200 2000] 

[        200       90000    64000000 62500000000] 

[False  True False  True] 



### Datentypen

In [13]:
l = [1, 2.0, 'hallo']
pril_1 = [1, 2, 3, 4]
# l_2 = [200, 300, 400, 500]nt(l)
print(type(l[0]))
print(type(l[1]))
print(type(l[2]))

<class 'int'>
<class 'float'>
<class 'str'>


In [14]:
a = np.array([1, 2.0, 'hallo'])
print(a)
print(type(a[0]))
print(type(a[1]))
print(type(a[2]))

['1' '2.0' 'hallo']
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Recheneffizienz

**`zip`**:

In [15]:
for element in [1, 2, 3, 4]:
    print(element)



l_1 = [1, 2, 3, 4]
l_2 = [200, 300, 400, 500]

print()

for i in range(len(l_1)):
    print( l_1[i] + l_2[i] )
    

print()
    
# zip


for el_1, el_2 in zip(l_1, l_2):
    
    print(el_1, el_2)


1
2
3
4

201
302
403
504

1 200
2 300
3 400
4 500


In [16]:
# listen elementweise verrechnen

def add_element_wise(l_1, l_2):
    
    added_list = []
    
    for el_1, el_2 in zip(l_1, l_2):
        
        added_list.append(el_1 + el_2)
        
    return added_list

add_element_wise(l_1, l_2)

[201, 302, 403, 504]

In [17]:
l_1 = []
l_2 = []

for i in range(10000000):
    
    l_1.append(i)
    l_2.append((i + 2) * 100)
    
add_element_wise(l_1, l_2)

[200,
 301,
 402,
 503,
 604,
 705,
 806,
 907,
 1008,
 1109,
 1210,
 1311,
 1412,
 1513,
 1614,
 1715,
 1816,
 1917,
 2018,
 2119,
 2220,
 2321,
 2422,
 2523,
 2624,
 2725,
 2826,
 2927,
 3028,
 3129,
 3230,
 3331,
 3432,
 3533,
 3634,
 3735,
 3836,
 3937,
 4038,
 4139,
 4240,
 4341,
 4442,
 4543,
 4644,
 4745,
 4846,
 4947,
 5048,
 5149,
 5250,
 5351,
 5452,
 5553,
 5654,
 5755,
 5856,
 5957,
 6058,
 6159,
 6260,
 6361,
 6462,
 6563,
 6664,
 6765,
 6866,
 6967,
 7068,
 7169,
 7270,
 7371,
 7472,
 7573,
 7674,
 7775,
 7876,
 7977,
 8078,
 8179,
 8280,
 8381,
 8482,
 8583,
 8684,
 8785,
 8886,
 8987,
 9088,
 9189,
 9290,
 9391,
 9492,
 9593,
 9694,
 9795,
 9896,
 9997,
 10098,
 10199,
 10300,
 10401,
 10502,
 10603,
 10704,
 10805,
 10906,
 11007,
 11108,
 11209,
 11310,
 11411,
 11512,
 11613,
 11714,
 11815,
 11916,
 12017,
 12118,
 12219,
 12320,
 12421,
 12522,
 12623,
 12724,
 12825,
 12926,
 13027,
 13128,
 13229,
 13330,
 13431,
 13532,
 13633,
 13734,
 13835,
 13936,
 14037,
 1

In [18]:
a_1 = np.array(l_1)
a_2 = np.array(l_2)

In [19]:
a_1 + a_2

array([       200,        301,        402, ..., 1009999897, 1009999998,
       1010000099])

In [20]:
%timeit add_element_wise(l_1, l_2)

579 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
%timeit a_1 + a_2

7.9 ms ± 377 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
